### ISSUE TITLE
Writing directly to todo.txt file maybe? 

### ISSUE THREAD

**Issue by mabkenar** [bicarbon8/todoTxtWebUi#27]
I find this web app really clean and beautiful, and I really like the design. Kudos for your great work :)

At the moment I am desperately looking for any todo.txt app on my Ubuntu desktop which is (a) capable of sorting and filtering based on projects, contexts, and priorities, and (b) make it possible to sync the todo.txt file using ownCloud etc. for mobile/the-other-desktop sync.

todoTxtWebUi is the closest thing I have found to fulfil (a). But how can it be changed to fulfil (b)?

I know that it might be impossible to do using only HTML, Javascript and CSS. But I sincerely hope there is a way around it. Is there any? Is it possible, e.g. in the case of Bulldog, to run a microserver on the desktop or something similar to have direct writing permissions on the todo.txt file?

**Comment by bicarbon8** [comment]
unfortunately, at this time I've found no way to do what you're asking other than allowing you to download and save over top of an existing file. sorry I couldn't be of more help

**Comment by mabkenar** [comment]
I have recently found TiddlyWiki, which has a Firefox extention (desktop/android) called TiddlyFox:
https://addons.mozilla.org/en-US/firefox/addon/tiddlyfox/?src=search
The extension does exactly this: it makes it possible to save a file to the file system by click of a button on the web page. This video shows it:
https://www.youtube.com/watch?v=bsWE7jXPbb0

I know this is not a standard solution, but it is something that previously has been done. Just my two cents.

**Comment by bicarbon8** [comment]
Unfortunately I'm not willing to add any dependencies such as those used in
the older versions of TiddlyWiki as I want this webapp to be purely HTML,
JavaScript and CSS with no plugins or extensions required. Sorry this
probably isn't the answer you were hoping for.
