### ISSUE TITLE
Ubuntu webapp?

### ISSUE THREAD

**Issue by mabkenar** [bicarbon8/todoTxtWebUi#28]
How easy it is to package this app using the Ubuntu webapps SDK?

https://developer.ubuntu.com/en/web/

**Comment by mabkenar** [comment]
As I understand from todoTxtTests.js, this is using LocalStorage for saving todo.txt file internally. The Ubuntu Webapps guide says that it supports LocalStorage: https://developer.ubuntu.com/en/web/ubuntu-webapps-guide/

**Comment by bicarbon8** [comment]
Yes, this webapp uses localstorage and has the ability to generate a download file as well.

unfortunately I've not used the ubuntu webapps SDK so I'll leave it with you to figure out. Let me know if I can help answer any other questions about the application itself.

**Comment by mabkenar** [comment]
Thank you. I will look into it if I find some time. But it's not very likely ;/
